/*
 * Copyright (c) 2025 Fraunhofer FOKUS and others. All rights reserved.
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contact: mosaic@fokus.fraunhofer.de
 */

package org.eclipse.mosaic.interactions.traffic;

import static org.apache.commons.lang3.builder.ToStringStyle.SHORT_PREFIX_STYLE;

import org.eclipse.mosaic.lib.objects.fleet.RideReservation;
import org.eclipse.mosaic.lib.objects.fleet.FleetVehicleData;
import org.eclipse.mosaic.rti.api.Interaction;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;

import java.io.Serial;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Contains updates of fleet vehicles and all known ride reservations,
 * generated by the DRT-taxi device within SUMO.
 */
public final class FleetServiceUpdates extends Interaction {

    @Serial
    private static final long serialVersionUID = 1L;

    /**
     * String identifying the type of this interaction.
     */
    public final static String TYPE_ID = createTypeIdentifier(FleetServiceUpdates.class);

    private final List<FleetVehicleData> fleetVehicles;
    private final List<RideReservation> reservations;

    /**
     * Constructor using fields.
     *
     * @param time          Timestamp of this interaction, unit: [ns]
     * @param fleetVehicles Fleet vehicles that are available.
     * @param reservations  All available ride reservations, including assigned reservations.
     */
    public FleetServiceUpdates(long time, List<FleetVehicleData> fleetVehicles, List<RideReservation> reservations) {
        super(time);
        this.fleetVehicles = fleetVehicles;
        this.reservations = reservations;
    }

    public List<FleetVehicleData> getFleetVehicles() {
        return fleetVehicles;
    }

    public List<RideReservation> getReservations() {
        return reservations;
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(5, 17)
                .append(fleetVehicles)
                .append(reservations)
                .toHashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (obj == this) {
            return true;
        }
        if (obj.getClass() != getClass()) {
            return false;
        }

        FleetServiceUpdates other = (FleetServiceUpdates) obj;
        return new EqualsBuilder()
                .append(this.fleetVehicles, other.fleetVehicles)
                .append(this.reservations, other.reservations)
                .isEquals();
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this, SHORT_PREFIX_STYLE)
                .appendSuper(super.toString())
                .append("fleetVehicles", fleetVehicles.stream().map(t -> t.getVehicleData().getName()).collect(Collectors.joining(",")))
                .append("reservations", reservations.stream().map(RideReservation::getId).collect(Collectors.joining(",")))
                .toString();
    }

}
